// packages/react-ds/src/components/Breadcrumb/BreadcrumbItem.tsx
import * as React from 'react'

import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Breadcrumb.module.scss'

export const BreadcrumbItem: React.FunctionComponent<React.HTMLProps<
  HTMLDivElement
>> = ({ children, className = '', ...rest }) => {
  return (
    <div className={classNames(styles.JSMBreadcrumbItem, className)} {...rest}>
      {children}
    </div>
  )
}

// packages/vue-ds/src/components/Breadcrumb/BreadcrumbItem.vue
<template>
  <div class="JSMBreadcrumbItem">
    <slot />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component({})
export default class BreadcrumbItem extends Vue {}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Breadcrumb.module.scss';
</style>
