// packages/react-ds/src/components/Breadcrumb/index.tsx
import * as React from 'react'

import { IBreadcrumb } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Breadcrumb.module.scss'

export const Breadcrumb: React.FunctionComponent<
  IBreadcrumb & React.HTMLAttributes<HTMLOrSVGElement>
> = ({ children, color = 'default', className = '', ...rest }) => {
  return (
    <nav
      className={classNames(styles.breadcrumb, styles[color], className)}
      aria-label="breadcrumb"
      {...rest}
    >
      {children}
    </nav>
  )
}

export const BreadcrumbItem: React.FunctionComponent<React.HTMLProps<
  HTMLDivElement
>> = ({ children, className = '', ...rest }) => {
  return (
    <div className={classNames(styles.breadcrumbItem, className)} {...rest}>
      {children}
    </div>
  )
}

// packages/vue-ds/src/components/Breadcrumb/Breadcrumb.vue
<template>
  <nav :class="breadcrumbClass" aria-label="breadcrumb">
    <slot />
  </nav>
</template>

<script lang="ts">
import { IBreadcrumb } from '@juntossomosmais/venice-types'
import { Component, Vue, Prop } from 'vue-property-decorator'

@Component({})
export default class Breadcrumb extends Vue {
  @Prop({ default: 'default' }) color!: IBreadcrumb['color']

  get breadcrumbClass() {
    return ['breadcrumb', this.color]
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Breadcrumb.module.scss';
</style>
