// packages/react-ds/src/components/Spinner/Spinner.tsx
import React from 'react'

import { ISpinner } from '@venice/core/models'
import styles from '@venice/styles/components/Spinner.module.scss'

const Spinner = ({ color = 'default', size = 36, ...rest }: ISpinner) => {
  return (
    <div
      className={`
      ${styles.spinner}
      ${styles[color]}
    `}
      style={{
        height: size,
        width: size,
      }}
      role="progressbar"
      aria-busy="true"
      {...rest}
    ></div>
  )
}

export default Spinner

// packages/vue-ds/src/components/Spinner/Spinner.vue
<template>
  <div
    :class="['spinner', color]"
    :style="{ height: `${size}px`, width: `${size}px` }"
    role="progressbar"
    aria-busy="true"
  ></div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'

import { ISpinner } from '@venice/core/models'

@Component
export default class Spinner extends Vue {
  @Prop({ default: 'default' }) color!: ISpinner['color']
  @Prop({ default: 36 }) size!: ISpinner['size']
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Spinner.module.scss';
</style>
