// packages/react-ds/src/components/Pagination/index.tsx
import React, { useState, useEffect, useCallback } from 'react'

import classNames from 'classnames/bind'

import {
  getRangeIndexes,
  hasNextRange,
  hasPreviousRange,
} from '@venice/core/helpers/Pagination'
import { IPagination } from '@venice/core/models'
import styles from '@venice/styles/components/Pagination.module.scss'

// TODO: these icons should be replaced when there is an icon library
import AngleLeft from './icons/AngleLeft'
import AngleRight from './icons/AngleRight'
import PaginationIndex from './PaginationIndex'

const debounce = (func: () => void, wait: number) => {
  let timer = 0

  return () => {
    clearTimeout(timer)
    timer = window.setTimeout(func, wait)
  }
}

export const Pagination: React.FunctionComponent<IPagination> = ({
  count = 1,
  page = 1,
  isLoading = false,
  onChange = () => null,
  className,
  ...props
}) => {
  const maxPhoneWidth = 420
  const [isMobile, setIsMobile] = useState(false)

  const checkDevice = () => setIsMobile(window.innerWidth <= maxPhoneWidth)

  const isInvalid = () => page < 1 || page > count || count < 1

  const hasNextCondition = isMobile
    ? hasNextRange(2, page, count)
    : hasNextRange(3, page, count)

  const hasPreviousCondition = isMobile
    ? hasPreviousRange(2, page)
    : hasPreviousRange(3, page)

  const nextPage = () => onChange(page + 1)
  const prevPage = () => onChange(page - 1)
  const onSelectPage = (newPage: number) => onChange(newPage)

  const [startOfRange, endOfRange] = getRangeIndexes(count, page, isMobile)
  const getAllIndexes = useCallback(
    () => Array.from(Array(count + 1).keys()).slice(1),
    [count]
  )
  const range = getAllIndexes().slice(startOfRange, endOfRange)

  useEffect(() => {
    checkDevice()
    const debouncedCheck = debounce(checkDevice, 200)

    window.addEventListener('resize', debouncedCheck)
    return () => window.removeEventListener('resize', debouncedCheck)
  }, [])

  return !isInvalid() ? (
    <section
      className={classNames(
        styles.pagination,
        { [styles.isMobile]: isMobile },
        className
      )}
      {...props}
    >
      <div
        className={classNames(styles.container, {
          center: !hasNextCondition && !hasPreviousCondition,
          [styles.justifyContentEnd]: hasNextCondition && !hasPreviousCondition,
          [styles.justifyContentStart]:
            !hasNextCondition && hasPreviousCondition,
        })}
      >
        {hasPreviousCondition && (
          <button
            className={styles.paginationButton}
            disabled={isLoading}
            onClick={prevPage}
          >
            <AngleLeft width="12" height="23" viewBox="-1 3 12 7" />
          </button>
        )}
        {range.map((pageIndex) => (
          <PaginationIndex
            key={pageIndex}
            page={pageIndex}
            count={count}
            isCurrentPage={page === pageIndex}
            onSelect={onSelectPage}
          />
        ))}
        {hasNextCondition && (
          <button
            className={styles.paginationButton}
            disabled={isLoading}
            onClick={nextPage}
          >
            <AngleRight width="12" height="23" viewBox="-3 3 12 7" />
          </button>
        )}
      </div>
    </section>
  ) : null
}

// packages/vue-ds/src/components/Pagination/Pagination.vue
<template>
  <section v-if="!isInvalid" :class="PaginationClass">
    <div :class="PaginationContainerClass">
      <button
        v-if="hasPreviousCondition"
        class="paginationButton"
        :disabled="isLoading"
        @click="prevPage"
      >
        <AngleLeft :width="12" :height="23" :viewBox="'-1 3 12 7'" />
      </button>
      <div
        v-for="(currentPage, idx) in range"
        :key="idx"
        class="indexWrapper"
        :class="page === currentPage ? 'active' : ''"
        :data-marker="page === currentPage && `de ${count}`"
      >
        <div class="paginationIndex" @click="selectPage(currentPage)">
          <p>{{ currentPage }}</p>
        </div>
      </div>
      <button
        v-if="hasNextCondition"
        class="paginationButton"
        :disabled="isLoading"
        @click="nextPage"
      >
        <AngleRight :width="12" :height="23" :viewBox="'-3 3 12 7'" />
      </button>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'

import {
  getRangeIndexes,
  hasNextRange,
  hasPreviousRange,
} from '@venice/core/helpers/Pagination'
import { IPagination } from '@venice/core/models'

// TODO: these icons should be replaced when there is an icon library
import AngleLeft from './icons/AngleLeft.vue'
import AngleRight from './icons/AngleRight.vue'

@Component({
  components: {
    AngleLeft,
    AngleRight,
  },
})
export default class Pagination extends Vue {
  @Prop({ default: 1 }) count!: IPagination['count']
  @Prop({ default: 1 }) page!: IPagination['page']
  @Prop({ default: false }) isLoading!: IPagination['isLoading']
  @Prop() onChange!: IPagination['onChange']
  @Prop() customClass!: IPagination['className']

  private maxPhoneWidth = 420
  private isMobile = false
  private range: number[] = []

  debounce = (func: () => void, wait: number) => {
    let timer: number

    return () => {
      clearTimeout(timer)
      timer = window.setTimeout(func, wait)
    }
  }

  checkDevice = () => window.innerWidth <= this.maxPhoneWidth

  setState() {
    this.isMobile = this.checkDevice()
    this.range = this.getRange
  }

  debouncedSetState = this.debounce(this.setState, 200)

  created() {
    this.setState()
    window.addEventListener('resize', this.debouncedSetState)
  }

  beforeDestroy() {
    window.removeEventListener('resize', this.debouncedSetState)
  }

  nextPage = () => this.onChange && this.onChange(this.page + 1)
  prevPage = () => this.onChange && this.onChange(this.page - 1)
  selectPage = (newPage: number) => this.onChange && this.onChange(newPage)

  get PaginationClass() {
    return ['pagination', this.isMobile ? 'isMobile' : '', this.customClass]
  }

  get PaginationContainerClass() {
    return [
      'container',
      this.hasNextCondition && !this.hasPreviousCondition
        ? 'justifyContentEnd'
        : '',
      !this.hasNextCondition && this.hasPreviousCondition
        ? 'justifyContentStart'
        : '',
    ]
  }

  get isInvalid() {
    return this.page < 1 || this.page > this.count || this.count < 1
  }

  get hasNextCondition() {
    return this.isMobile
      ? hasNextRange(2, this.page, this.count)
      : hasNextRange(3, this.page, this.count)
  }

  get hasPreviousCondition() {
    return this.isMobile
      ? hasPreviousRange(2, this.page)
      : hasPreviousRange(3, this.page)
  }

  get rangeLimits() {
    return getRangeIndexes(this.count, this.page, this.isMobile)
  }

  get getRange() {
    const allIndexes = Array.from(Array(this.count + 1).keys()).slice(1)
    const [startOfRange, endOfRange] = this.rangeLimits

    return allIndexes.slice(startOfRange, endOfRange)
  }
}
</script>

<style lang="scss" scoped>
@import '@venice/styles/components/Pagination.module.scss';
</style>
