// packages/react-ds/src/components/Stepper/index.tsx
import * as React from 'react'

import { IStepper } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Stepper.module.scss'

export const Stepper: React.FunctionComponent<IStepper> = ({
  steps = [],
  className,
  ...props
}) => {
  const isActive = React.useCallback(
    (completed: boolean): string => (completed ? styles['active'] : ''),
    []
  )

  const isLastActive = React.useCallback(
    (index: number): string => {
      const currentStep = steps[index]
      const nextStep = steps[index + 1]

      const currentStepIsTheLastCompleted =
        currentStep.completed && nextStep && !nextStep.completed

      return currentStepIsTheLastCompleted ? styles['last'] : ''
    },
    [steps]
  )

  return (
    <ul className={classNames(styles.stepper, className)} {...props}>
      {steps.map((item, index) => (
        <li
          key={index}
          className={`${styles.step} ${isActive(item.completed)} ${isLastActive(
            index
          )}`}
        >
          <span className={styles.title}>{item.title}</span>
          {item.subtitle && (
            <span className={styles.subtitle}>{item.subtitle}</span>
          )}
        </li>
      ))}
    </ul>
  )
}

// packages/vue-ds/src/components/Stepper/Stepper.vue
<template>
  <ul class="stepper">
    <li
      class="step"
      :class="`${isActive(step.completed)} ${isLastActive(idx)}`"
      v-for="(step, idx) in steps"
      :key="idx"
    >
      <span class="title">{{ step.title }}</span>
      <span class="subtitle" v-if="step.subtitle">{{ step.subtitle }}</span>
    </li>
  </ul>
</template>

<script lang="ts">
import { IStepper } from '@juntossomosmais/venice-types'
import { Component, Vue, Prop } from 'vue-property-decorator'

@Component
export default class Stepper extends Vue {
  @Prop({ default: [], type: Array }) steps!: IStepper['steps']

  isActive(completed: boolean) {
    return completed ? 'active' : ''
  }

  isLastActive(index: number) {
    const currentStep = this.steps[index]
    const nextStep = this.steps[index + 1]

    const currentStepIsTheLastCompleted =
      currentStep.completed && nextStep && !nextStep.completed

    return currentStepIsTheLastCompleted ? 'last' : ''
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Stepper.module.scss';
</style>
