// packages/react-ds/src/components/SplitButton/SplitButton.tsx
import * as React from 'react'

import { ISplitButton } from '@venice/core/models'
import styles from '@venice/styles/components/SplitButton.module.scss'

import Button from '../Button/Button'

interface ISplitButtonProps extends ISplitButton {
  /** React Element */
  children: React.ReactNode
}

const SplitButton: React.FC<ISplitButtonProps> = ({
  text,
  children,
  color = 'default',
  size = 'large',
  direction = 'rtl',
  menuFitButtonContainer = false,
  openType = 'hover',
  ...props
}: ISplitButtonProps) => {
  const [isOpen, setIsOpen] = React.useState(false)

  const clickType = openType === 'click' && isOpen ? styles.active : ''

  return (
    <nav
      className={`${styles.SplitButton}
      ${styles[openType]}
      ${clickType}`}
      {...props}
    >
      <Button
        color={color}
        size={size}
        aria-expanded={isOpen}
        onClick={() => setIsOpen(!isOpen)}
      >
        {text}
        <span className={styles.caret}></span>
      </Button>
      <div
        className={`${styles.dropdown}
                    ${styles[size]}
                    ${styles[color]}
                    ${styles[direction]}
                    ${menuFitButtonContainer ? styles.fitbutton : ''}`}
        role="menu"
      >
        {children}
      </div>
    </nav>
  )
}

export default SplitButton

// packages/vue-ds/src/components/SplitButton/SplitButton.vue
<template>
  <nav :class="componentClass">
    <Button
      :color="color"
      :size="size"
      @click="onClickButton"
      v-bind="{ 'aria-expanded': isOpen }"
    >
      <slot name="text">{{ text }}</slot>
      <span class="caret"></span>
    </Button>
    <div :class="dropdownClass" role="menu">
      <slot />
    </div>
  </nav>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'

import { ISplitButton } from '@venice/core/models'

import Button from '../Button/Button.vue'

@Component({
  components: {
    Button,
  },
})
export default class SplitButton extends Vue {
  @Prop({ default: 'default' }) color!: ISplitButton['color']
  @Prop({ default: 'large' }) size!: ISplitButton['size']
  @Prop({ default: 'rtl' }) direction!: ISplitButton['direction']
  @Prop({ default: false })
  menuFitButtonContainer!: ISplitButton['menuFitButtonContainer']
  @Prop({ default: 'hover' })
  openType!: ISplitButton['openType']
  @Prop({ type: String }) text!: ISplitButton['text']

  private isOpen = false

  get componentClass() {
    const clickType = this.openType === 'click' && this.isOpen ? 'active' : ''

    return ['SplitButton', this.openType, clickType]
  }

  get dropdownClass() {
    return [
      'dropdown',
      this.direction,
      this.size,
      this.color,
      this.menuFitButtonContainer ? 'fitbutton' : '',
    ]
  }

  onClickButton() {
    this.isOpen = !this.isOpen
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/SplitButton.module.scss';
</style>
