// packages/react-ds/src/components/SplitButton/index.tsx
import * as React from 'react'

import { ISplitButton } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'

import styles from '@venice/styles/components/SplitButton.module.scss'

import { Button } from '../Button'

export interface ISplitButtonProps extends ISplitButton {
  /** React Element */
  children: React.ReactNode
}

export const SplitButton: React.FunctionComponent<ISplitButtonProps> = ({
  text,
  children,
  color = 'default',
  size = 'large',
  direction = 'rtl',
  isFitMenu = false,
  openType = 'hover',
  ...props
}) => {
  const [isOpen, setIsOpen] = React.useState(false)

  const clickType = openType === 'click' && isOpen

  const navClassNames = classNames(styles.splitButton, styles[openType], {
    [styles.active]: clickType,
  })

  const menuClassNames = classNames(
    styles.dropdown,
    styles[size],
    styles[color],
    styles[direction],
    { [styles.fitbutton]: isFitMenu }
  )

  return (
    <nav className={navClassNames} {...props}>
      <Button
        className={styles['inner-button']}
        color={color}
        size={size}
        aria-expanded={isOpen}
        onClick={() => setIsOpen(!isOpen)}
      >
        {text}
        <span className={styles.caret}></span>
      </Button>
      <div className={menuClassNames} role="menu">
        {children}
      </div>
    </nav>
  )
}

// packages/vue-ds/src/components/SplitButton/SplitButton.vue
<template>
  <nav :class="componentClass">
    <Button
      :color="color"
      :size="size"
      @click="onClickButton"
      v-bind="{ 'aria-expanded': isOpen }"
      class="inner-button"
    >
      <slot name="text">{{ text }}</slot>
      <span class="caret"></span>
    </Button>
    <div :class="dropdownClass" role="menu">
      <slot />
    </div>
  </nav>
</template>

<script lang="ts">
import { ISplitButton } from '@juntossomosmais/venice-types'
import { Component, Vue, Prop } from 'vue-property-decorator'

import Button from '../Button/Button.vue'

@Component({
  components: {
    Button,
  },
})
export default class SplitButton extends Vue {
  @Prop({ default: 'default' }) color!: ISplitButton['color']
  @Prop({ default: 'large' }) size!: ISplitButton['size']
  @Prop({ default: 'rtl' }) direction!: ISplitButton['direction']
  @Prop({ default: false }) isFitMenu!: ISplitButton['isFitMenu']
  @Prop({ default: 'hover' }) openType!: ISplitButton['openType']
  @Prop({ type: String }) text!: ISplitButton['text']

  private isOpen = false

  get componentClass() {
    const clickType = this.openType === 'click' && this.isOpen ? 'active' : ''

    return ['splitButton', this.openType, clickType]
  }

  get dropdownClass() {
    return [
      'dropdown',
      this.direction,
      this.size,
      this.color,
      this.isFitMenu ? 'fitbutton' : '',
    ]
  }

  onClickButton() {
    this.isOpen = !this.isOpen
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/SplitButton.module.scss';
</style>
