// packages/react-ds/src/components/Button/Button.tsx
import React from 'react'

import { IButton, IDynamicComponentProps } from '@venice/core/models'
import styles from '@venice/styles/components/Button.module.scss'

import Spinner from '../Spinner/Spinner'

interface IButtonProps extends IButton {
  /** string */
  className?: string
  /** React Element */
  children?: React.ReactNode
  /** React Element | string */
  endIcon?: React.ReactNode | string
  /** React Element | string */
  startIcon?: React.ReactNode | string
  onClick: () => void
}

const ButtonComponent: React.FunctionComponent<IDynamicComponentProps &
  React.HTMLAttributes<HTMLOrSVGElement>> = ({
  as: Wrapper = 'button',
  children,
  ...rest
}) => {
  return <Wrapper {...rest}>{children}</Wrapper>
}

const Button: React.FunctionComponent<IButtonProps> = ({
  children,
  className = '',
  color = 'default',
  endIcon,
  href,
  isLoading = false,
  shape = 'round-square',
  size = 'large',
  startIcon,
  variant = 'filled',
  ...rest
}: IButtonProps) => {
  return (
    <>
      <ButtonComponent
        as={href ? 'a' : 'button'}
        role={href ? '' : 'button'}
        aria-busy={isLoading}
        className={`
          ${styles.btn}
          ${styles[color]}
          ${styles[variant]}
          ${styles[size]}
          ${styles[shape]}
          ${isLoading ? styles.isLoading : ''}
          ${className}
        `}
        {...(href && { href })}
        {...rest}
      >
        {isLoading && (
          <Spinner
            color={variant === 'filled' ? `${color}-contrast` : color}
            size={size === 'small' ? 16 : 24}
            className={`${styles.loading}`}
          />
        )}
        <>
          {startIcon && (
            <span className={`${styles.startIcon}`}>{startIcon}</span>
          )}
          <span className={`${styles.children}`}>{children}</span>
          {endIcon && <span className={`${styles.endIcon}`}>{endIcon}</span>}
        </>
      </ButtonComponent>
    </>
  )
}

export default Button

// packages/vue-ds/src/components/Button/Button.vue
<template>
  <component
    :is="href ? 'a' : 'button'"
    :class="buttonClass"
    :href="href"
    :role="href ? '' : 'button'"
    :aria-busy="isLoading"
    @click="$emit('click')"
  >
    <Spinner
      v-if="isLoading"
      :color="spinnerColor"
      :size="spinnerSize"
      class="loading"
    />
    <span class="startIcon">
      <!-- @slot To add icon at the beginning -->
      <slot name="startIcon" />
    </span>
    <span class="children">
      <!-- @slot To add something, like a text -->
      <slot />
    </span>
    <span class="endIcon">
      <!-- @slot To add icon at the end -->
      <slot name="endIcon" />
    </span>
  </component>
</template>

<script lang="ts">
import { IButton } from '@juntossomosmais/venice-types'
import { Component, Vue, Prop } from 'vue-property-decorator'

import Spinner from '../Spinner/Spinner.vue'

@Component({
  components: {
    Spinner,
  },
})
export default class Button extends Vue {
  @Prop({ default: 'default' }) color!: IButton['color']
  @Prop({ default: 'filled' }) variant!: IButton['variant']
  @Prop({ default: 'round-square' }) shape!: IButton['shape']
  @Prop({ default: 'large' }) size!: IButton['size']
  @Prop({ default: false }) isLoading!: IButton['isLoading']
  @Prop() href!: IButton['href']

  get buttonClass() {
    return [
      'button',
      this.color,
      this.variant,
      this.shape,
      this.size,
      this.isLoading ? 'isLoading' : '',
    ]
  }

  get spinnerColor() {
    return this.variant === 'filled' ? `${this.color}-contrast` : this.color
  }

  get spinnerSize() {
    return this.size === 'small' ? 16 : 24
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Button.module.scss';
</style>
