// packages/vue-ds/src/components/Checkbox/Checkbox.vue
<template>
  <div class="container">
    <label :for="selfId" class="label" :style="cursor">
      <input
        class="checkbox"
        type="checkbox"
        :id="selfId"
        :checked="value"
        @change="$emit('input', $event.target.checked)"
        v-bind="$attrs"
      />
      <span class="customCheckbox jsm-icon-check"></span>
      {{ label }}
    </label>
    <div v-if="error" class="error jsm-icon-alert">
      {{ error }}
    </div>
  </div>
</template>

<script lang="ts">
import { IField } from '@juntossomosmais/venice-types'
import uniqid from 'uniqid'
import { Component, Vue, Prop } from 'vue-property-decorator'

@Component({
  inheritAttrs: false,
})
export default class Checkbox extends Vue {
  @Prop({ default: '' }) label!: IField['label']
  @Prop({ default: '' }) error!: IField['error']
  @Prop({ default: false }) value!: boolean

  private selfId = this.$attrs.id || uniqid(`input__`)

  get cursor() {
    const isDisabled = 'disabled' in this.$attrs

    return {
      cursor: isDisabled ? 'not-allowed' : 'pointer',
    }
  }
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/CheckboxRadio.module.scss';
</style>

// packages/react-ds/src/components/Checkbox/index.tsx
import * as React from 'react'

import { IField } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'
import uniqid from 'uniqid'

import styles from '@venice/styles/components/CheckboxRadio.module.scss'

const InternalCheckbox = (
  {
    id,
    label,
    style,
    className,
    error,
    ...props
  }: IField & React.HTMLProps<HTMLInputElement>,
  ref?: React.Ref<HTMLInputElement>
) => {
  const selfId = id || uniqid(`input__`)
  const styleContainer = classNames(
    styles.container,
    { [styles.invalid]: Boolean(error) },
    className
  )
  const cursor = { cursor: props.disabled ? 'not-allowed' : 'pointer' }

  return (
    <div className={styleContainer} style={style}>
      <label htmlFor={selfId} className={styles.label} style={cursor}>
        <input
          className={styles.checkbox}
          type="checkbox"
          id={selfId}
          {...props}
          ref={ref}
        />
        <span className={`${styles.customCheckbox} jsm-icon-check`}></span>
        {label}
      </label>
      {error && <div className={`${styles.error} jsm-icon-alert`}>{error}</div>}
    </div>
  )
}

export const Checkbox = React.forwardRef(InternalCheckbox)
