// packages/vue-ds/src/components/Paper/Paper.vue
<template>
  <div class="paper">
    <slot />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component({})
export default class Paper extends Vue {}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Paper.module.scss';
</style>

// packages/react-ds/src/components/Paper/index.tsx
import * as React from 'react'

import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Paper.module.scss'

export const Paper: React.FunctionComponent<React.HTMLProps<
  HTMLDivElement
>> = ({ children, className = '', ...rest }) => {
  return (
    <div className={classNames(styles.paper, className)} {...rest}>
      {children}
    </div>
  )
}
