// packages/vue-ds/src/components/Breadcrumb/Breadcrumb.vue
<template>
  <nav :class="breadcrumbClass" aria-label="breadcrumb">
    <slot />
  </nav>
</template>

<script lang="ts">
import { IBreadcrumb } from '@juntossomosmais/venice-types'
import Vue, { PropOptions } from 'vue'

export default Vue.extend({
  name: 'Breadcrumb',
  props: {
    color: { default: 'default' } as PropOptions<IBreadcrumb['color']>,
  },
  computed: {
    breadcrumbClass() {
      return ['JSMBreadcrumb', `JSMBreadcrumb--${this.color}`]
    },
  },
})
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Breadcrumb.module.scss';
</style>

// packages/react-ds/src/components/Breadcrumb/Breadcrumb.tsx
import * as React from 'react'

import { IBreadcrumb } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Breadcrumb.module.scss'

export interface IBreadcrumbProps extends IBreadcrumb {
  /** string */
  className?: string
  /** React Element */
  children?: React.ReactNode
}

export const Breadcrumb: React.FunctionComponent<IBreadcrumbProps> = ({
  children,
  color = 'default',
  className = '',
  ...rest
}) => {
  return (
    <nav
      className={classNames(
        styles.JSMBreadcrumb,
        styles[`JSMBreadcrumb--${color}`],
        className
      )}
      aria-label="breadcrumb"
      {...rest}
    >
      {children}
    </nav>
  )
}
