// packages/vue-ds/src/components/Spinner/Spinner.vue
<template>
  <svg
    :class="['JSMSpinner', `JSMSpinner--${color}`]"
    :style="{ height: `${size}px`, width: `${size}px` }"
    role="progressbar"
    aria-busy="true"
    viewBox="0 0 66 66"
  >
    <circle
      :class="['JSMSpinner--circle']"
      fill="none"
      strokeWidth="6"
      strokeLinecap="round"
      cx="33"
      cy="33"
      r="30"
    ></circle>
  </svg>
</template>

<script lang="ts">
import { ISpinner } from '@juntossomosmais/venice-types'
import { Component, Vue, Prop } from 'vue-property-decorator'

@Component
export default class Spinner extends Vue {
  @Prop({ default: 'default' }) color!: ISpinner['color']
  @Prop({ default: 36 }) size!: ISpinner['size']
}
</script>

<style lang="scss" scoped>
@import '~@venice/styles/components/Spinner.module.scss';
</style>

// packages/react-ds/src/components/Spinner/index.tsx
import * as React from 'react'

import { ISpinner } from '@juntossomosmais/venice-types'
import classNames from 'classnames/bind'

import styles from '@venice/styles/components/Spinner.module.scss'

export interface ISpinnerProps extends ISpinner {
  /** string */
  className?: string
}

export const Spinner = ({
  className = '',
  color = 'default',
  size = 36,
  ...rest
}: ISpinnerProps) => {
  return (
    <svg
      className={classNames(
        styles.JSMSpinner,
        styles[`JSMSpinner--${color}`],
        className
      )}
      style={{
        fontSize: size,
        height: size,
        width: size,
      }}
      role="progressbar"
      aria-busy="true"
      viewBox="0 0 66 66"
      {...rest}
    >
      <circle
        className={styles[`JSMSpinner--circle`]}
        fill="none"
        strokeWidth="6"
        strokeLinecap="round"
        cx="33"
        cy="33"
        r="30"
      ></circle>
    </svg>
  )
}
